apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kafka
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  dependsOn:
    - name: flux
  path: ./mgmt-cluster/addons/kafka
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  dependsOn:
    - name: flux
  path: ./apps/infra
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: infra-couchdb
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   retryInterval: 30s
#   timeout: 30s
#   dependsOn:
#     - name: flux
#   path: ./apps/infra-couchdb
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   postBuild:
#     substituteFrom:
#       - kind: ConfigMap
#         name: cluster-config