apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gha-controller
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30s
  dependsOn:
    - name: flux
  path: ./mgmt-cluster/addons/gha-runners/controller
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
