apiVersion: v1
kind: Namespace
metadata:
  name: emails
---
apiVersion: v1
kind: Service
metadata:
  name: emails
  namespace: emails
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: emails
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emails
  namespace: emails
  labels:
    app: emails
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emails
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: emails
    spec:
      containers:
        - name: workload
          image: paulcarltondae/emails:0.0.1 # {"$imagepolicy": "flux-system:emails-mgr"}
          env:
            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "management.endpoint.health.probes.add-additional-paths": true
                }
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 64Mi

